name: build

on:
  push:
    branches:
    tags:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up go 1.18
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: build and test
        run: |
          go test -timeout=60s -race
          go build -race
      - name: run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50
